### PR TITLE
Adding pipelines to process the data

### PR DESCRIPTION
**Pull request by smartmeerkat**
Hello everyone!

First of all I would like to thank for this handy and lightweight package to @WendellAdriel and all contributors, you saved me a lot of time.

I ran into some limitations in functionality during development and would like to suggest an option to extend it.

Let's start from example with simple data structure.

I'm receiving array of data in PascalCase:
```
{
    "FullName": "John Doe",
    "DetailedData": {
        "FirstName": "John",
        "LastName": "Doe"
    }
}
```

All of my variables and rules in DTOs is in camelCase:
```
class FullNameDTO extends ValidatedDTO
{
    public string $fullName;

    public DetailedDataDTO $detailedData;
    ...
}
```
```
class DetailedDataDTO extends ValidatedDTO
{
    public string $firstName;

    public string $lastName;
    ...
```

And I have to put this data into a table, the fields of which are in the snake_case.

The easiest and most flexible solution, in my opinion, was to pass the $data array before and $validatedData after validation through the pipeline of functions passed to the constructor. [I used the built in solution in laravel for creating pipelines.](https://laravel.com/docs/10.x/helpers#pipeline)

Here is some example of the pipe class:
```
class ConvertKeysToCamelCasePipe
{
    public function handle(array $array, Closure $next)
    {
        foreach ($array as $key => $value) {
            if ($key == ($camelCaseKey = Str::camel($key))) {
                continue;
            }

            $array[$camelCaseKey] = $value;
            unset($array[$key]);
        }

        return $next($array);
    }
}
```
You can read more about it in the documentation link above.

Creating the DTO object in this case looks like that:
```
$dto = FullNameDTO::fromJson(
    '{"FullName":"John Doe","DetailedData":{"firstName":"John","lastName":"Doe"}}',
    [
        'pipeline_before_validation' => [ConvertKeysToCamelCasePipe::class],
        'pipeline_before_export' => [ConvertKeysToSnakeCasePipe::class]
    ]
);
```

You can add any closure or pipe class to this array to process the data inside the DTO however you want.
Besides we can use $config parameter in future to extend DTO`s functionality.

Here are the responses of the methods toArray and toJson:
```
[
  "full_name" => "John Doe"
  "detailed_data" => App\DTOs\DetailedDataDTO^ {#758...}
]
```
```
{
    "full_name": "John Doe",
    "detailed_data": {
        "firstName": "John",
        "lastName": "Doe"
    }
}
```

As you can see, so far the pipeline does not affect nested DTOs. Let's fix it!
I extend the ValidatedDTO and DTOCast class a little bit so now you can pass the config variable to the nested DTO constructors if you want.
To do this you need to pass a configuration parameter to the declared DTOCast:
```
protected function casts(): array
{
    return [
        'detailedData' => new DTOCast(DetailedDataDTO::class, $this->config)
    ];
}
```

Now let's create another pipe class that will extract all nested DTOs into arrays and pass it to the constructor:
```
class ExtractNestedDTOsToArraysPipe
{
    public function handle(array $array, Closure $next)
    {
        foreach ($array as $key => $value) {
            if ($value instanceof ValidatedDTO) {
                $array[$key] = $value->toArray();
            }
        }

        return $next($array);
    }
}
```
```
$dto = FullNameDTO::fromJson(
    '{"FullName":"John Doe","DetailedData":{"firstName":"John","lastName":"Doe"}}',
    [
        'pipeline_before_validation' => [ConvertKeysToCamelCasePipe::class],
        'pipeline_before_export' => [
            ExtractNestedDTOsToArraysPipe::class,
            ConvertKeysToSnakeCasePipe::class
        ]
    ]
);
```

Let's check the answers:
```
[
  "full_name" => "John Doe"
  "detailed_data" => array:2 [
    "first_name" => "John"
    "last_name" => "Doe"
  ]
]
```
```
{
    "full_name": "John Doe",
    "detailed_data": {
        "first_name": "John",
        "last_name": "Doe"
    }
}
```

Perfect!

I added all these useful pipe classes to the src/Pipes folder so feel free to use them.

This can also be useful for clearing input data from prefixes and in a number of other cases.
The most important thing is that all this functionality is optional and will not slow down the work if you do not use it.

I find this functionality very useful and I will be glad if this PR is approved. I propose to discuss these changes. Feel free everyone to improve my changes.

### CODE REVIEW

**Comment by WendellAdriel** [comment]
Hey @smartmeerkat the PR is nice, but that was not my idea on how to add this kind of feature in the package.

Checking the issue created (#25) the idea is to have a way to map properties before the validation and/or when exporting the DTO to another structure/type.

I created this package with the vision that things should be simple to use.
My idea for creating this feature is only to add two more **abstract methods** in the `ValidatedDTO`:

```php
abstract protected function mapBeforeValidation(): array;

abstract protected function mapBeforeExport(): array;
```

These methods will simply map properties to other names if needed:

```php
protected function mapBeforeValidation(): array
{
    return [
        'FullName' => 'fullName',
    ];
}

protected function mapBeforeExport(): array
{
    return [
        'fullName' => 'full_name',
    ];
}
```

The idea is that the `mapBeforeValidation` will get the data passed, for example a request with the property `FullName`, and it will map it to the field in the **DTO** that will be `fullName`. So when the **DTO** is created you don't have access to the `FullName` anymore, only `fullName`.

The idea for the `mapBeforeExport` is to get the **DTO** properties and map them to other properties, like transforming the `fullName` to `full_name` or whatever is needed like `customer_name`.

The Pipes that you added are nice but for me, it's out of the scope of the package.
The package should provide a simple way for the users to map the data before the validation and before "exporting" the DTO to another type of structure/type, but that can be achieved in a simpler way with the methods I described.

Do you want to work on this or should I work on it?

**Review by WendellAdriel — CHANGES_REQUESTED** [review]
Check my comment above how we should implement this feature

**Comment by smartmeerkat** [comment]
Thanks for your feedback.
> Do you want to work on this or should I work on it?

Sure I can do that but on weekends. Is that ok?

**Comment by WendellAdriel** [comment]
@smartmeerkat I won't be able to work on this on this week as well because of my 9-5 job, so it's all good!
I'm going to assign the issue to you and close this PR so you can open a new one with the other solution.

**Pull request closed without merging**
