### PR TITLE
tests :: refactor some tests

### PR DESCRIPTION
**Pull request by falahatiali**
refactor some tests

### CODE REVIEW

**Review by WendellAdriel — APPROVED** [review]
Thanks for the contribution @falahatiali 💪

**Comment by falahatiali** [comment]
@WendellAdriel thanks from you for this wonderful package

**Comment by WendellAdriel** [comment]
@falahatiali There's no contributors list, in the README we have a link to the contributors' page: https://github.com/WendellAdriel/laravel-validated-dto/graphs/contributors but this is not managed by me, it's GitHub that creates this page and adds the list of contributors.

**Comment by falahatiali** [comment]
> page

Thanks for your reply, yes i know it. but it was so weird for me why I dont add to the list.

**Comment by WendellAdriel** [comment]
> Thanks for your reply, yes i know it. but it was so weird for me why I dont add to the list.

Sorry, but IDK why either and it's not in my control 😢

**Pull request merged**
